#!/bin/bash

# save not hidden paths in the file
# needed for manual (!) sync without external hard drive...
# instead of diff use comm

if [ $1 ] && [ $2 ]; then
    tmp_file=$(mktemp)
    find "$1" ! -regex ".*/\..*" > "$tmp_file"
    sort -o "$2" "$tmp_file"
    rm -f "$tmp_file"
else
    echo "usage: <path to generate> <path to output file>"
    exit 1
fi
