#!/bin/bash

# save not hidden paths in the file
# needed for manual (!) sync without external hard drive...

if [ $1 ] && [ $2 ]; then
    find "$1" ! -regex ".*/\..*" > "$2"
else
    echo "usage: <path to generate> <path to output file>"
    exit 1
fi
