#!/bin/bash

# https://wiki.archlinux.org/index.php/simple_stateful_firewall#Firewall_for_a_single_machine

iptables-restore < /etc/iptables/empty.rules

iptables -X
iptables -F

iptables -N TCP
iptables -N UDP

iptables -P FORWARD DROP
iptables -P OUTPUT ACCEPT

iptables -P INPUT DROP
iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -A INPUT -i lo -j ACCEPT
iptables -A INPUT -m conntrack --ctstate INVALID -j DROP
iptables -A INPUT -p icmp --icmp-type 8 -m conntrack --ctstate NEW -j ACCEPT
iptables -A INPUT -p udp -m conntrack --ctstate NEW -j UDP
iptables -A INPUT -p tcp --syn -m conntrack --ctstate NEW -j TCP
iptables -A INPUT -p udp -j REJECT --reject-with icmp-port-unreachable
iptables -A INPUT -p tcp -j REJECT --reject-with tcp-reset
iptables -A INPUT -j REJECT --reject-with icmp-proto-unreachable

# opening ports
#iptables -A INPUT -s 0/0 -p tcp --dport 6892 -j ACCEPT
#iptables -A INPUT -s 0/0 -p udp --dport 6892 -j ACCEPT

# save rules
iptables-save > /etc/iptables/iptables.rules

# print the iptables
iptables -L
