#!/bin/bash

# show current song
# use mpc

options="%artist% - %title%"

state="$(mpc -f "$options" | sed -n '2p')"
if [[ ! "$state" ]]; then
    echo "stop"
else
    #state="$(mpc -f "$options" | sed -n -e 's/^\(\[.*\]\).*/\1/p')"
    playing="$(mpc -f "$options" | head -n 1)"
    echo "$playing"
fi
